name: Run Collector

on:
  push:
    branches: [Compliance-Engine]
    
jobs:
  run-collector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Configure GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > "${HOME}/gcp-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-key.json" >> $GITHUB_ENV

      - name: Run GCP Access Collector
        run: python3 engine/GCPAccess.py
