name: Run Collector

on:
  push:
    branches: [Compliance-Engine]
    
jobs:
  run-collector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Run GCP Access Collector
        env: 
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Run GCP Access Collector
        run: python3 engine/GCPAccess.py
